/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  BulkJobs: () => import('#controllers/bulk_jobs_controller'),
  CandidatOnboarding: () => import('#controllers/candidat_onboarding_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Educations: () => import('#controllers/educations_controller'),
  EmployeeSkills: () => import('#controllers/employee_skills_controller'),
  Employees: () => import('#controllers/employees_controller'),
  ExerciseResults: () => import('#controllers/exercise_results_controller'),
  Experiences: () => import('#controllers/experiences_controller'),
  Notes: () => import('#controllers/notes_controller'),
  Onboarding: () => import('#controllers/onboarding_controller'),
  Organizations: () => import('#controllers/organizations_controller'),
  Skills: () => import('#controllers/skills_controller'),
  SuperAdmin: () => import('#controllers/super_admin_controller'),
  SupportPlanSteps: () => import('#controllers/support_plan_steps_controller'),
}
