/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Employees: () => import('#controllers/employees_controller'),
  ExerciseResults: () => import('#controllers/exercise_results_controller'),
  Organizations: () => import('#controllers/organizations_controller'),
}
