/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CandidatePaymentSchema extends BaseModel {
  static $columns = [
    'amountCents',
    'createdAt',
    'currency',
    'employeeId',
    'grantedByUserId',
    'id',
    'organizationId',
    'paidAt',
    'productCode',
    'provider',
    'refundedAt',
    'revokeReason',
    'revokedAt',
    'status',
    'stripeCheckoutSessionId',
    'stripePaymentIntentId',
    'updatedAt',
    'userId',
    'withdrawalWaivedAt',
  ] as const
  $columns = CandidatePaymentSchema.$columns
  @column()
  declare amountCents: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare employeeId: number | null
  @column()
  declare grantedByUserId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare organizationId: number
  @column.dateTime()
  declare paidAt: DateTime | null
  @column()
  declare productCode: string
  @column()
  declare provider: string
  @column.dateTime()
  declare refundedAt: DateTime | null
  @column()
  declare revokeReason: string | null
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare stripeCheckoutSessionId: string | null
  @column()
  declare stripePaymentIntentId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number | null
  @column.dateTime()
  declare withdrawalWaivedAt: DateTime | null
}

export class ContactRequestSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'id',
    'message',
    'name',
    'organization',
    'phone',
    'status',
    'type',
    'updatedAt',
  ] as const
  $columns = ContactRequestSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string
  @column()
  declare name: string
  @column()
  declare organization: string | null
  @column()
  declare phone: string | null
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EducationSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'degree',
    'description',
    'employeeId',
    'endDate',
    'id',
    'isCurrent',
    'school',
    'sortOrder',
    'startDate',
    'updatedAt',
  ] as const
  $columns = EducationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare degree: string
  @column()
  declare description: string | null
  @column()
  declare employeeId: number
  @column.date()
  declare endDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCurrent: boolean
  @column()
  declare school: string
  @column()
  declare sortOrder: number | null
  @column.date()
  declare startDate: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmployeeSkillSchema extends BaseModel {
  static $columns = ['createdAt', 'employeeId', 'id', 'level', 'skillId', 'updatedAt'] as const
  $columns = EmployeeSkillSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare employeeId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare level: number
  @column()
  declare skillId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmployeeSynthesisSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'employeeId',
    'executiveSummaryOverride',
    'expertCommentsShared',
    'expertNotesInternal',
    'id',
    'organizationId',
    'shareStatus',
    'sharedAt',
    'sharedByUserId',
    'updatedAt',
  ] as const
  $columns = EmployeeSynthesisSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare employeeId: number
  @column()
  declare executiveSummaryOverride: string | null
  @column()
  declare expertCommentsShared: string | null
  @column()
  declare expertNotesInternal: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare organizationId: number
  @column()
  declare shareStatus: string
  @column.dateTime()
  declare sharedAt: DateTime | null
  @column()
  declare sharedByUserId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmployeeSchema extends BaseModel {
  static $columns = [
    'accountType',
    'advisorId',
    'advisorNotes',
    'createdAt',
    'currentRole',
    'deletedAt',
    'email',
    'erasureRequestedAt',
    'id',
    'name',
    'onboarded',
    'organizationId',
    'status',
    'summary',
    'targetRole',
    'updatedAt',
    'userId',
  ] as const
  $columns = EmployeeSchema.$columns
  @column()
  declare accountType: string
  @column()
  declare advisorId: number | null
  @column()
  declare advisorNotes: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentRole: string
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare erasureRequestedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare onboarded: boolean
  @column()
  declare organizationId: number
  @column()
  declare status: string
  @column()
  declare summary: string | null
  @column()
  declare targetRole: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number | null
}

export class ExerciseResultSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'data',
    'date',
    'duration',
    'employeeId',
    'id',
    'progressPercent',
    'qualitativeAnalysis',
    'quantitativeScore',
    'status',
    'type',
    'updatedAt',
  ] as const
  $columns = ExerciseResultSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: any
  @column.date()
  declare date: DateTime | null
  @column()
  declare duration: number | null
  @column()
  declare employeeId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare progressPercent: number | null
  @column()
  declare qualitativeAnalysis: string | null
  @column()
  declare quantitativeScore: number | null
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ExperienceSchema extends BaseModel {
  static $columns = [
    'company',
    'createdAt',
    'description',
    'employeeId',
    'endDate',
    'id',
    'isCurrent',
    'sortOrder',
    'startDate',
    'title',
    'type',
    'updatedAt',
  ] as const
  $columns = ExperienceSchema.$columns
  @column()
  declare company: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare employeeId: number
  @column.date()
  declare endDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCurrent: boolean
  @column()
  declare sortOrder: number | null
  @column.date()
  declare startDate: DateTime
  @column()
  declare title: string
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MediaSchema extends BaseModel {
  static $columns = [
    'bytes',
    'cloudinaryPublicId',
    'createdAt',
    'deliveryType',
    'entityId',
    'entityType',
    'format',
    'id',
    'kind',
    'organizationId',
    'originalFilename',
    'resourceType',
    'updatedAt',
    'uploadedById',
  ] as const
  $columns = MediaSchema.$columns
  @column()
  declare bytes: number
  @column()
  declare cloudinaryPublicId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deliveryType: string
  @column()
  declare entityId: number
  @column()
  declare entityType: string
  @column()
  declare format: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare organizationId: number
  @column()
  declare originalFilename: string
  @column()
  declare resourceType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare uploadedById: number | null
}

export class NoteSchema extends BaseModel {
  static $columns = [
    'authorId',
    'content',
    'createdAt',
    'deletedAt',
    'employeeId',
    'exerciseResultId',
    'id',
    'organizationId',
    'supportPlanStepId',
    'updatedAt',
    'visibility',
  ] as const
  $columns = NoteSchema.$columns
  @column()
  declare authorId: number
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare employeeId: number
  @column()
  declare exerciseResultId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare organizationId: number
  @column()
  declare supportPlanStepId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare visibility: string
}

export class NotificationSchema extends BaseModel {
  static $columns = [
    'body',
    'createdAt',
    'id',
    'meta',
    'readAt',
    'status',
    'title',
    'type',
    'updatedAt',
    'userId',
  ] as const
  $columns = NotificationSchema.$columns
  @column()
  declare body: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare meta: any | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class OnboardingTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'token', 'usedAt', 'userId'] as const
  $columns = OnboardingTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: number
}

export class OrganizationSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'id',
    'isPlatform',
    'logoPublicId',
    'logoUrl',
    'name',
    'slug',
    'updatedAt',
  ] as const
  $columns = OrganizationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPlatform: boolean
  @column()
  declare logoPublicId: string | null
  @column()
  declare logoUrl: string | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'token', 'usedAt', 'userId'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: number
}

export class PdfExportSchema extends BaseModel {
  static $columns = [
    'advisorUserId',
    'createdAt',
    'employeeId',
    'errorMessage',
    'fileName',
    'filePath',
    'finishedAt',
    'id',
    'mimeType',
    'organizationId',
    'size',
    'startedAt',
    'status',
    'updatedAt',
    'userId',
  ] as const
  $columns = PdfExportSchema.$columns
  @column()
  declare advisorUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare employeeId: number
  @column()
  declare errorMessage: string | null
  @column()
  declare fileName: string | null
  @column()
  declare filePath: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mimeType: string | null
  @column()
  declare organizationId: number | null
  @column()
  declare size: number | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class QueueJobSchema extends BaseModel {
  static $columns = [
    'acquiredAt',
    'data',
    'error',
    'executeAt',
    'finishedAt',
    'id',
    'queue',
    'score',
    'status',
    'workerId',
  ] as const
  $columns = QueueJobSchema.$columns
  @column()
  declare acquiredAt: bigint | number | null
  @column()
  declare data: string
  @column()
  declare error: string | null
  @column()
  declare executeAt: bigint | number | null
  @column()
  declare finishedAt: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queue: string
  @column()
  declare score: bigint | number | null
  @column()
  declare status: string
  @column()
  declare workerId: string | null
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'cronExpression',
    'everyMs',
    'fromDate',
    'id',
    'lastRunAt',
    'name',
    'nextRunAt',
    'payload',
    'runCount',
    'runLimit',
    'status',
    'timezone',
    'toDate',
  ] as const
  $columns = QueueScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cronExpression: string | null
  @column()
  declare everyMs: bigint | number | null
  @column.dateTime()
  declare fromDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column()
  declare payload: string
  @column()
  declare runCount: number
  @column()
  declare runLimit: number | null
  @column()
  declare status: string
  @column()
  declare timezone: string
  @column.dateTime()
  declare toDate: DateTime | null
}

export class SkillSchema extends BaseModel {
  static $columns = [
    'category',
    'createdAt',
    'deletedAt',
    'id',
    'name',
    'organizationId',
    'slug',
    'updatedAt',
  ] as const
  $columns = SkillSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare organizationId: number | null
  @column()
  declare slug: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SupportPlanStepExerciseSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'exerciseType',
    'id',
    'sortOrder',
    'supportPlanStepId',
    'updatedAt',
  ] as const
  $columns = SupportPlanStepExerciseSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare exerciseType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sortOrder: number | null
  @column()
  declare supportPlanStepId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SupportPlanStepSchema extends BaseModel {
  static $columns = [
    'advisorId',
    'completed',
    'createdAt',
    'description',
    'dueDate',
    'employeeId',
    'endedAt',
    'id',
    'instructions',
    'isLocked',
    'locationOrLink',
    'notes',
    'scheduledAt',
    'sortOrder',
    'status',
    'title',
    'updatedAt',
  ] as const
  $columns = SupportPlanStepSchema.$columns
  @column()
  declare advisorId: number | null
  @column()
  declare completed: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column.date()
  declare dueDate: DateTime | null
  @column()
  declare employeeId: number
  @column.dateTime()
  declare endedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare instructions: string | null
  @column()
  declare isLocked: boolean
  @column()
  declare locationOrLink: string | null
  @column()
  declare notes: string | null
  @column.dateTime()
  declare scheduledAt: DateTime | null
  @column()
  declare sortOrder: number
  @column()
  declare status: string
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'email',
    'id',
    'name',
    'onboardingCompletedAt',
    'organizationId',
    'password',
    'role',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime()
  declare onboardingCompletedAt: DateTime | null
  @column()
  declare organizationId: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
