export enum ExerciseType {
  MOTIVATION = 'MOTIVATION',
  VALUES = 'VALUES',
  PERSONALITY = 'PERSONALITY',
  COMPETENCIES = 'COMPETENCIES',
  LIFE_CURVE = 'LIFE_CURVE',
  CV_ANALYSIS = 'CV_ANALYSIS',
  TARGETING = 'TARGETING',
  DISC = 'DISC',
  CIRCLE_OF_CONTROL = 'CIRCLE_OF_CONTROL',
  SKILL_MAPPING = 'SKILL_MAPPING',
}
